### ISSUE TITLE
Pipe spacing

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Flappy-Bird-Clone#5]
I think the pipe spacing is still buggy? (See recent commit: a5750bd17110f971180f29ca22b2345a23fa062a from @pckerneis.)

I'd like to match the original flappy bird game.

![screen shot 2018-03-08 at 10 11 55 pm](https://user-images.githubusercontent.com/191758/37188552-c3c3af76-231d-11e8-8fec-921eaca510c0.png)

**Comment by techiepriyansh** [comment]
Hey Dan!!! I fixed this issue and updated the code to ES6. As I am not comfortable with gitting, you can access the code here: https://drive.google.com/file/d/1ijRWYSfMuTbvYv1Vd-nUOPuCbJKBoXek/view?usp=drivesdk

**Comment by rhbvkleef** [comment]
I am pretty sure this issue can be closed. (See MR #1)

**Comment by rhbvkleef** [comment]
If @techiepriyansh his code was submitted in #1, the issue wasn't fixed.

**Comment by pckerneis** [comment]
Yeah sorry, I went too fast on this one! With @rhbvkleef's fix it should be fine!

**Comment by DaGuT** [comment]
https://github.com/CodingTrain/Flappy-Bird-Clone/pull/13
Fixed, but it can go beyond the screen sometimes
